language: c
cache: ccache
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
before_script: which ccache > /dev/null && ccache -s || echo "CCache is not available."
script:
  ./configure && make -j2 all examples check && make -C tests run_local

sudo: false
