language: c
dist: trusty
sudo: false
cache: ccache
env:
 global:
  - ARCH=x64
  # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
  #   via the "travis encrypt" command using the project repo's public key
  - secure: "tPKKZA6ftcQskn9H0iN2aQP0IluQ9kmwf8CQJ+CB9hPfMq0ItZQptQ9ZrSLEJ+lZfr/BpdJ//v439eJFYf7ejejQ3HACdpJlcNR6i7sAjFV45tCogHhs40wsUP/v0FRaMElutNX4uiMSiNCA7olgqJCfNExv8BECkKwM1Nb5dhgENO40j+Q+e3kqeN5GnXoHoK0kb+hLMYbHDigkwwmWXNjbiw/tsg5Luxt4rvbwth9OxqSVY2HH3FC/1wEREBOm/KditH/CjtQ39df9cBKPL8WZn2i9CPEtWbhCcPmW97aUl6c2P7os2qWFAkQzspEvSBnbyqDtMEqJdrsdFZy9DkQOOKLx2QNLbJJuxZBsMoo3FS6KsNz7o3zZteQAhboRb0tc/R4gWmMS3bK6ewZRrOOcH2jtRKpVhwWwFQUMZlMfF8dMSiRQ1pMnHiy+8MwENWgAGbgZQ8wfkwLw8SJiTjhvpudIFezikMp6VzKkcK1Z8lQINe0UDYtxh4+C4pfL9xTdstM+XWbFLvYEZAPObu44XlGAE/uRfBz+OWnKZYQ0pjnDwdYa5v+YsH8MNThA8eD1E4Fcoh0EkCW40+g+TR2gF8ThO05SHr7VQvHlDSJRFb3ZDFnNVowDwRztPkzU08n5MP7i46yEETw9Wo974bxEHkwAI7GdCCY9jzs60xQ="

matrix:
 include:
 - name: "Linux GCC"
   os: linux
   compiler: gcc
   before_script:
    - ./configure --install-deps --disable-lz4-ext --prefix="$PWD/dest"

install:
 - ccache -s || echo "CCache is not available."
 - rm -rf artifacts dest
 - mkdir dest artifacts

before_script:
script:
- make -j2 all examples check && make -j2 -C tests build
- if [[ $RUN_INTEGRATION_TESTS != y ]]; then make -C tests run_local ; fi
- make install
- if [[ -z $NO_ARTIFACTS ]]; then (cd dest && tar cvzf ../artifacts/librdkafka-${CC}.tar.gz .) ; fi
- for distro in $ADDITIONAL_BUILDS ; do packaging/tools/distro-build.sh $distro || exit 1 ; done
- if [[ $COPYRIGHT_CHECK == y ]]; then make copyright-check ; fi
- if [[ $RUN_INTEGRATION_TESTS == y ]]; then (cd tests && ./interactive_broker_version.py -c "make quick" 2.2.0) ; fi

deploy:
  provider: s3
  access_key_id:
    secure: "m8FQrFesK0xSS1wHo2S7cuWkpO7VB91dBmj1XIYLRXZSkbMpKBJATcFcHNbrAp3slEp7wLAnT7CHrQ4ccQi4H68Z7mjEwdq4VKRE+7zqJ/feK8MOFNeSHWLQzgwLUYlRlc9+tzLNwxMuL2ilWgdjKOArsUVHo9LEKNfQ3T6zCJU="
  secret_access_key:
    secure: "GE6O0gk5VRervntCKAmczfBdSOvbr9bouJ15H2rpcOgHi8KTDEjI/NS69eLiRRSHBCARtcRqN4wfgy+/dn7D1VklY8a1rAKu02wGjw+fq7k7GVSSmynR/aF619R4SIABsaAhNCwswXnLHuLlq8HFk5ulG3z8DUvYBczB45bWZfQ="
  bucket: librdkafka-ci-packages
  region: us-west-1
  skip_cleanup: true
  local-dir: artifacts
  upload-dir: librdkafka/p-librdkafka__bld-travis__plat-${TRAVIS_OS_NAME}__arch-${ARCH}__tag-${TRAVIS_TAG}__sha-${TRAVIS_COMMIT}__bid-${TRAVIS_JOB_NUMBER}
  on:
    repo: edenhill/librdkafka
    all_branches: true
    tags: true
    on: $NO_ARTIFACTS != y

addons:
  coverity_scan:
    project:
      name: "edenhill/librdkafka"
      description: "librdkafka"
    notification_email: rdkafka+coverity@edenhill.se
    build_command_prepend: "./configure"
    build_command: "make -j2"
    branch_pattern: coverity_scan
